SVG=Card.svg

all: jokers clubs spades hearts diamonds


jokers: joker1.png joker2.png joker3.png

joker1.png: $(SVG)
	inkscape --export-png=joker1.png --export-area=-640:0:-123:697 "$(SVG)"
joker2.png: $(SVG)
	inkscape --export-png=joker2.png --export-area=0:0:517:697 "$(SVG)"
joker3.png: $(SVG)
	inkscape --export-png=joker3.png --export-area=640:0:1157:697 "$(SVG)"


clubs: c2.png c3.png c4.png c5.png c6.png c7.png c8.png c9.png c0.png cj.png cq.png ck.png c1.png

c2.png: $(SVG)
	inkscape --export-png=c2.png --export-area=-3840:820:-3323:1517 "$(SVG)"
c3.png: $(SVG)
	inkscape --export-png=c3.png --export-area=-3200:820:-2683:1517 "$(SVG)"
c4.png: $(SVG)
	inkscape --export-png=c4.png --export-area=-2560:820:-2043:1517 "$(SVG)"
c5.png: $(SVG)
	inkscape --export-png=c5.png --export-area=-1920:820:-1403:1517 "$(SVG)"
c6.png: $(SVG)
	inkscape --export-png=c6.png --export-area=-1280:820:-763:1517 "$(SVG)"
c7.png: $(SVG)
	inkscape --export-png=c7.png --export-area=-640:820:-123:1517 "$(SVG)"
c8.png: $(SVG)
	inkscape --export-png=c8.png --export-area=0:820:517:1517 "$(SVG)"
c9.png: $(SVG)
	inkscape --export-png=c9.png --export-area=640:820:1157:1517 "$(SVG)"
c0.png: $(SVG)
	inkscape --export-png=c0.png --export-area=1280:820:1797:1517 "$(SVG)"
cj.png: $(SVG)
	inkscape --export-png=cj.png --export-area=1920:820:2437:1517 "$(SVG)"
cq.png: $(SVG)
	inkscape --export-png=cq.png --export-area=2560:820:3077:1517 "$(SVG)"
ck.png: $(SVG)
	inkscape --export-png=ck.png --export-area=3200:820:3717:1517 "$(SVG)"
c1.png: $(SVG)
	inkscape --export-png=c1.png --export-area=3840:820:4357:1517 "$(SVG)"


spades: s2.png s3.png s4.png s5.png s6.png s7.png s8.png s9.png s0.png sj.png sq.png sk.png s1.png

s2.png: $(SVG)
	inkscape --export-png=s2.png --export-area=-3840:1640:-3323:2337 "$(SVG)"
s3.png: $(SVG)
	inkscape --export-png=s3.png --export-area=-3200:1640:-2683:2337 "$(SVG)"
s4.png: $(SVG)
	inkscape --export-png=s4.png --export-area=-2560:1640:-2043:2337 "$(SVG)"
s5.png: $(SVG)
	inkscape --export-png=s5.png --export-area=-1920:1640:-1403:2337 "$(SVG)"
s6.png: $(SVG)
	inkscape --export-png=s6.png --export-area=-1280:1640:-763:2337 "$(SVG)"
s7.png: $(SVG)
	inkscape --export-png=s7.png --export-area=-640:1640:-123:2337 "$(SVG)"
s8.png: $(SVG)
	inkscape --export-png=s8.png --export-area=0:1640:517:2337 "$(SVG)"
s9.png: $(SVG)
	inkscape --export-png=s9.png --export-area=640:1640:1157:2337 "$(SVG)"
s0.png: $(SVG)
	inkscape --export-png=s0.png --export-area=1280:1640:1797:2337 "$(SVG)"
sj.png: $(SVG)
	inkscape --export-png=sj.png --export-area=1920:1640:2437:2337 "$(SVG)"
sq.png: $(SVG)
	inkscape --export-png=sq.png --export-area=2560:1640:3077:2337 "$(SVG)"
sk.png: $(SVG)
	inkscape --export-png=sk.png --export-area=3200:1640:3717:2337 "$(SVG)"
s1.png: $(SVG)
	inkscape --export-png=s1.png --export-area=3840:1640:4357:2337 "$(SVG)"


hearts: h2.png h3.png h4.png h5.png h6.png h7.png h8.png h9.png h0.png hj.png hq.png hk.png h1.png

h2.png: $(SVG)
	inkscape --export-png=h2.png --export-area=-3840:2460:-3323:3157 "$(SVG)"
h3.png: $(SVG)
	inkscape --export-png=h3.png --export-area=-3200:2460:-2683:3157 "$(SVG)"
h4.png: $(SVG)
	inkscape --export-png=h4.png --export-area=-2560:2460:-2043:3157 "$(SVG)"
h5.png: $(SVG)
	inkscape --export-png=h5.png --export-area=-1920:2460:-1403:3157 "$(SVG)"
h6.png: $(SVG)
	inkscape --export-png=h6.png --export-area=-1280:2460:-763:3157 "$(SVG)"
h7.png: $(SVG)
	inkscape --export-png=h7.png --export-area=-640:2460:-123:3157 "$(SVG)"
h8.png: $(SVG)
	inkscape --export-png=h8.png --export-area=0:2460:517:3157 "$(SVG)"
h9.png: $(SVG)
	inkscape --export-png=h9.png --export-area=640:2460:1157:3157 "$(SVG)"
h0.png: $(SVG)
	inkscape --export-png=h0.png --export-area=1280:2460:1797:3157 "$(SVG)"
hj.png: $(SVG)
	inkscape --export-png=hj.png --export-area=1920:2460:2437:3157 "$(SVG)"
hq.png: $(SVG)
	inkscape --export-png=hq.png --export-area=2560:2460:3077:3157 "$(SVG)"
hk.png: $(SVG)
	inkscape --export-png=hk.png --export-area=3200:2460:3717:3157 "$(SVG)"
h1.png: $(SVG)
	inkscape --export-png=h1.png --export-area=3840:2460:4357:3157 "$(SVG)"


diamonds: d2.png d3.png d4.png d5.png d6.png d7.png d8.png d9.png d0.png dj.png dq.png dk.png d1.png

d2.png: $(SVG)
	inkscape --export-png=d2.png --export-area=-3840:3280:-3323:3977 "$(SVG)"
d3.png: $(SVG)
	inkscape --export-png=d3.png --export-area=-3200:3280:-2683:3977 "$(SVG)"
d4.png: $(SVG)
	inkscape --export-png=d4.png --export-area=-2560:3280:-2043:3977 "$(SVG)"
d5.png: $(SVG)
	inkscape --export-png=d5.png --export-area=-1920:3280:-1403:3977 "$(SVG)"
d6.png: $(SVG)
	inkscape --export-png=d6.png --export-area=-1280:3280:-763:3977 "$(SVG)"
d7.png: $(SVG)
	inkscape --export-png=d7.png --export-area=-640:3280:-123:3977 "$(SVG)"
d8.png: $(SVG)
	inkscape --export-png=d8.png --export-area=0:3280:517:3977 "$(SVG)"
d9.png: $(SVG)
	inkscape --export-png=d9.png --export-area=640:3280:1157:3977 "$(SVG)"
d0.png: $(SVG)
	inkscape --export-png=d0.png --export-area=1280:3280:1797:3977 "$(SVG)"
dj.png: $(SVG)
	inkscape --export-png=dj.png --export-area=1920:3280:2437:3977 "$(SVG)"
dq.png: $(SVG)
	inkscape --export-png=dq.png --export-area=2560:3280:3077:3977 "$(SVG)"
dk.png: $(SVG)
	inkscape --export-png=dk.png --export-area=3200:3280:3717:3977 "$(SVG)"
d1.png: $(SVG)
	inkscape --export-png=d1.png --export-area=3840:3280:4357:3977 "$(SVG)"


clean:
	rm {joker{1,2,3},{c,s,h,d}{2,3,4,5,6,7,8,9,0,j,q,k,1}}.png 2>/dev/null || exit 0

